version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release

before_build:
- ps: (New-Object System.Net.WebClient).DownloadFile('https://dot.net/v1/dotnet-install.ps1', "$env:appveyor_build_folder\dotnet-install.ps1")
- ps: ./dotnet-install.ps1 -Channel LTS
- dotnet restore
